version: '3'
services:
  web:
    build: .
    ports:
      - 80:9001
    environment:
      PORT: 9001
      NODE_ENV: production
      RETHINKDB_URL: rethinkdb://db:28015
      DB_NAME: vortex
    depends_on:
      - db
  db:
    image: "rethinkdb:2.3"
    ports:
      - 8081:8080
    volumes:
      - "${PWD}/data:/data"
